# Generated by Django 3.2.7 on 2021-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=32)),
                ('payload', models.CharField(max_length=64)),
            ],
        ),
    ]
