# Generated by Django 3.2.7 on 2021-09-16 18:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_model', models.CharField(max_length=32, unique=True)),
                ('handler', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('N', 'nothing'), ('Trim', 'trim'), ('PTM', 'pad to multiple'), ('Timestamp', 'time stamp')], default=('N', 'nothing'), max_length=32), size=None)),
                ('output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('N', 'nothing'), ('C', 'console'), ('T', 'terminal')], default=('N', 'nothing'), max_length=32), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='configuration',
            field=models.ForeignKey(db_column='SensorConfiguration.sensor_model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='SensorsProcessing.sensorconfiguration'),
        ),
    ]
