# Generated by Django 3.2.7 on 2021-09-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0002_auto_20210916_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorconfiguration',
            old_name='sensor_model',
            new_name='configuration_name',
        ),
        migrations.AddField(
            model_name='sensorconfiguration',
            name='sensor',
            field=models.ForeignKey(db_column='Sensor.model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_name', to='SensorsProcessing.sensor'),
        ),
    ]
