# Generated by Django 3.2.7 on 2021-09-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0003_auto_20210916_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='configuration',
            field=models.ForeignKey(db_column='SensorConfiguration.configuration_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='SensorsProcessing.sensorconfiguration'),
        ),
    ]
