# Generated by Django 3.2.7 on 2021-09-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0004_alter_sensor_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorconfiguration',
            old_name='configuration_name',
            new_name='sensor_model',
        ),
        migrations.RemoveField(
            model_name='sensorconfiguration',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='configuration',
            field=models.ForeignKey(db_column='SensorConfiguration.sensor_model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='SensorsProcessing.sensorconfiguration'),
        ),
    ]
