# Generated by Django 3.2.7 on 2021-09-17 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0005_auto_20210916_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorconfiguration',
            name='output',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('N', 'nothing'), ('Console', 'console'), ('File', 'file')], default=('N', 'nothing'), max_length=32), size=None),
        ),
    ]
