# Generated by Django 3.2.7 on 2021-09-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0006_auto_20210917_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='configuration',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='model',
            field=models.ForeignKey(db_column='SensorConfiguration.sensor_model', on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='SensorsProcessing.sensorconfiguration'),
        ),
    ]
