# Generated by Django 3.2.7 on 2021-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorsProcessing', '0007_auto_20210917_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensorconfiguration',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='sensorconfiguration',
            name='output',
        ),
        migrations.AddField(
            model_name='sensorconfiguration',
            name='handler',
            field=models.ManyToManyField(related_name='handler', to='SensorsProcessing.HandlerChoice'),
        ),
        migrations.AddField(
            model_name='sensorconfiguration',
            name='output',
            field=models.ManyToManyField(related_name='output', to='SensorsProcessing.OutputChoice'),
        ),
    ]
